minipy:main.cpp PyInterpreter.cpp CommandLineParser.cpp  simple.tab.c
	$(CXX) $(CFLAGS) main.cpp PyInterpreter.cpp CommandLineParser.cpp  simple.tab.c -o $(ROOT)/bin/minipy -L../lib -last -llexer
	@echo
	@echo
	@echo
	@echo Compilation DONE,GOTO bin/ folder to find the "minipy" program
